#ifndef SEMESTRAL_PROJECT_PHARMACY_DELETE_REQUEST_H
#define SEMESTRAL_PROJECT_PHARMACY_DELETE_REQUEST_H


struct PharmacyDeleteRequest {
    char* name;
};

#endif //SEMESTRAL_PROJECT_PHARMACY_DELETE_REQUEST_H
